[package]
name = "mock"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_derive = "1.0.219"
chrono = "0.4.40"
log = "0.4.27"
log4rs = "1.3.0"